### ISSUE TITLE
Docker Compose version please 

### ISSUE THREAD

**Issue by tigerinus** [Cormanz/smartgpt#32]
Thanks!

**Comment by Cormanz** [comment]
Hi, I would love to add this, but I'm not well acquainted with Docker Compose. If anyone else is interested in contributing this, feel free!

**Comment by tigerinus** [comment]
I've come up with a `Dockerfile`:

```Dockerfile
# Use the official Rust image as the base image
FROM rust:latest

# Set the working directory inside the container
WORKDIR /app

# Copy the entire project directory into the container
COPY . .

# Install cargo-edit to manage dependencies
RUN cargo install cargo-edit

# Install the required dependencies
RUN cargo fetch

# Build the project
RUN cargo build --release

# Set the entrypoint command to run the SmartGPT application
CMD ["cargo", "run", "--release"]
```

You will need to release it officially to Docker Hub, before we can come up with a `docker-compose.yml`. (Yes, Docker Compose supports build directly, but pulling it from Docker Hub is a lot easier for most people)

**Comment by tigerinus** [comment]
Assuming your image on Docker Hub is `Cormanz/smartgpt:latest`, here a `docker-compose.yml`:

```yaml
version: '3.8'
services:
  smartgpt:
    image: Cormanz/smartgpt:latest
    volumes:
      - ./config.yml:/app/config.yml
    environment:
      - RUST_BACKTRACE=1
    command: ["cargo", "run", "--release"]
```
